name: crack-agent
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip=25.1
  - pip:
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.12
      - aiosignal==1.3.2
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==3.7.1
      - async-timeout==4.0.3
      - attrs==25.3.0
      - Brotli==1.0.9
      - certifi==2025.4.26
      - charset-normalizer==3.3.2
      - click==8.2.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - dotenv==0.9.9
      - exceptiongroup==1.3.0
      - fastapi==0.115.12
      - ffmpy==0.6.0
      - filelock==3.17.0
      - fonttools==4.58.2
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - gmpy2==2.2.1
      - gradio==3.50.2
      - gradio_client==0.6.1
      - greenlet==3.2.3
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.33.0
      - idna==3.10
      - imageio==2.37.0
      - importlib_resources==6.5.2
      - Jinja2==3.1.6
      - jiter==0.10.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - langchain==0.1.20
      - langchain-community==0.0.38
      - langchain-core==0.1.53
      - langchain-text-splitters==0.0.2
      - langsmith==0.1.147
      - lazy_loader==0.4
      - MarkupSafe==2.1.5
      - marshmallow==3.26.1
      - matplotlib==3.10.3
      - mkl_fft==1.3.11
      - mkl_random==1.2.8
      - mkl-service==2.4.0
      - mpmath==1.3.0
      - multidict==6.4.4
      - mypy_extensions==1.1.0
      - narwhals==1.42.1
      - networkx==3.4.2
      - numpy==1.26.4
      - openai==1.86.0
      - opencv-python==4.11.0.86
      - orjson==3.10.18
      - packaging==23.2
      - pandas==2.3.0
      - pillow==10.4.0
      - propcache==0.3.2
      - pydantic==2.11.5
      - pydantic_core==2.33.2
      - pydub==0.25.1
      - pyparsing==3.2.3
      - PySocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - PyYAML==6.0.2
      - referencing==0.36.2
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rpds-py==0.25.1
      - scikit-image==0.25.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - six==1.17.0
      - sniffio==1.3.1
      - SQLAlchemy==2.0.41
      - starlette==0.46.2
      - sympy==1.13.3
      - tenacity==8.5.0
      - tifffile==2025.5.10
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - typing_extensions==4.12.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.3.0
      - uvicorn==0.22.0
      - websockets==11.0.3
      - wheel==0.45.1
      - win-inet-pton==1.1.0
      - yarl==1.20.1
